### ISSUE TITLE
Huge Memory Use 

### ISSUE THREAD

**Issue by marcosmorais** [fserre/sgen#2]
When used for FFT with n = 10 and k=7,  complex char data type, the memory usage is superior to 128Gb. Is it a feature?
...
[info] running main -n 10 -k 7 -r 1 -hw complex fixedpoint 4 4 dft
...
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed: ArrayDeque too big - cannot allocate ArrayDeque of length 1073741824
...

**Comment by fserre** [comment]
Hello!
Thank you for trying SGen, and for the bug report! It was due to a poor choice of data structure.
It has been fixed (da56ffd), and the generator should now be working more smoothly.

Best,

François
